### ISSUE TITLE
Investigate whether all the features work fine in mobile

### ISSUE THREAD

**Issue by manaswinidas** [manaswinidas/Notes-app#17]
Currently, all the features work fine in web, the main goal is to check whether everything works the same in Android

## Expected Behavior

Check whether all the buttons and all the functionalities are working just fine, this may require a screen recording of both the working web and mobile editions

## Context

The student has to set up a proper development environment for Cordova Android

## Your Environment

* Operating System and version (desktop or mobile): Fedora(desktop)
* Link to your project:

**Comment by Nikhil-Ladha** [comment]
I guess we are good to close this issue too, since I have already shared them with you @manaswinidas .
